### ISSUE TITLE
TWILIO SMS API INTEGRATION

### ISSUE THREAD

**Issue by simlexx-k** [igweze/wizgrade#10]
How can I integrate Twilio SMS API into the system? 
I have tried putting in my Twilio credentials into the database, table wizgrade_sms but it is not working.
After I set up this we can talk about licensing.

**Comment by igweze** [comment]
@simlexx-k So sorry for the late reply. Please, wizGrade upgrade coming soon will cover this.

Please, don't forget to star/like my project if you like it above. Thanks

Best Regards

**Comment by simlexx-k** [comment]
All right, and the support for php 8 please.
