### ISSUE TITLE
Error message when adding staff in Staff HR

### ISSUE THREAD

**Issue by Jameswnjihia** [igweze/wizgrade#11]
Hi guys and Mr Igweze, 
Congrat Mr Igweze  on the dedicating your energy and time on developing this great App. I'll see what I'll do to support you. 
I have an issue when adding a staff in Staff HR. It has been showing this error,  ' Ooops Database  Error: SQLSTATE[H000]: General error: 1366  Incorrect integer value: "for column 'rank 'at row 1
Anybody is invited to help especially Mr Igweze. 
Thanks

**Comment by igweze** [comment]
@Jameswnjihia You are highly welcome and so sorry for the late reply.

Locate and update this PHP file https://github.com/igweze/wizgrade/blob/master/sources/adminPage/commonPage/staffBioManager.php. This will solve your problem. I just updated the file.

Best Regards

**Comment by Jameswnjihia** [comment]
Thanks Mr Igweze.
My utmost appreciation
