### ISSUE TITLE
How to Edit or remove and re-publish class result

### ISSUE THREAD

**Issue by cvictor12** [igweze/wizgrade#12]
In a situation where one has computed and published a class result and wish to correct one or two students score which can alter the entire class position. How do I go about this ?

**Comment by igweze** [comment]
@cvictor12  Good Day,

So sorry for the late reply. Just saw your message.

Meanwhile, the system doesn't allow editing of result owns its computed and published to discourage abuse of the system.

However, in some special case, we can help you revert it back to editing stage.

Moreso, should I make it possible to perform this task in the wizgrade updates and please kindly give reason on why should I do so?

Best Regards
