### ISSUE TITLE
LOGIN ACCESS for Students/Parents, Bursar, Principal, head teachers

### ISSUE THREAD

**Issue by thefaloye** [igweze/wizgrade#2]
How can I create login access for students, parents, Principals, Head Teachers and other users of the system?

I can only access the system through Super Admin.

**Comment by wizgrade** [comment]
@thefaloye, 
Login as admin, select staff HR from menu and add your staffs. Then go to global configuration in the menu, click on school setup and you will see s school configuration form to add school admin. Meanwhile, after adding, go back to staff HR, click on manage staff, search for this staff, click on task drop-down button. You will see reset/reset, click on it and assign staff ID ie username & password.

Moreso, for class/form teacher, you need to select a school section, go Assign Manager and assign a class and repeat the step up to assign a username and password.

Hence, for students and parents login, enter a school section and register a student/s using manual or bulk upload or accept an online registration. It automatically assign the student and parent a regno (username) and a password (which is usually password, however if you prefer randomly generated password, locate wizGradeConfigs.php in the root folder and go line 69 or locate $generatePass = 0; replace it to 1.

Lastly, every user in the system can change their password once the login.

**Comment by lecrosoft** [comment]
Hello.am new here...and I must tell u ..uv really done a great job on dis app..pls where exactly will I find d script file and d source code to download and install?

Secondly I will need a full documentation dat will explain how to use d app starting from students admission, report card Creation , students promotion,how to use the voucher etc.

Thirdly can I reskin and customize d app..
As in d css and html?

Can the app cumulate both 1st term and second term result to make a 3rd term report card...

**Comment by packerdency** [comment]
![wizgrade](https://user-images.githubusercontent.com/16042462/80919724-8d4af500-8d63-11ea-894c-721525d4ca7a.JPG)
I get this message whenever I login,also there is no reset button to add staff accounts

**Comment by Omoseni** [comment]
What are the username and password for admin?
