### ISSUE TITLE
Where to download the zip source code and the file of this app on github and how to install and operate the app features

### ISSUE THREAD

**Issue by lecrosoft** [igweze/wizgrade#3]
Hello.am new here...and I must tell u ..uv really done a great job on dis app..pls where exactly will I find d script file and d source code to download and install?

Secondly I will need a full documentation dat will explain how to use d app starting from students admission, report card Creation , students promotion,how to use the voucher etc.

Thirdly can I reskin and customize d app..
As in d css and html?

*Can the app cumulate both 1st term and second term result to make a 3rd term report card...

Is this app a full source code?

**Comment by packerdency** [comment]
@igweze ,how can someone enable checking results using pin?

**Comment by igweze** [comment]
@lecrosoft Thanks for the compliment. Visit https://github.com/igweze/wizgrade, click on clone or download zip to get the source code.

wizGrade don't have documentation for now, however its easy to use with friendly user interface.

wizGrade can accumulate 1st, second and third term and give you overall annual result with just click of the button. 

You can add your CSS or HTML but never allowed to removes wizGrade logo and copyrights unless you buy a coffee

**Comment by igweze** [comment]
@packerdency I have ans your question in https://github.com/igweze/wizgrade/issues/4. Kindly check there

**Comment by packerdency** [comment]
How can one buy you a coffee cos you deserve more

**Comment by igweze** [comment]
@packerdency, you can donate through https://www.wizgrade.com or you can mail me.

Thanks so much
