### ISSUE TITLE
Results checking

### ISSUE THREAD

**Issue by packerdency** [igweze/wizgrade#4]
Good day,how can someone activate results checking using scratch card and how do we create parents account

**Comment by igweze** [comment]
@packerdency. For result checking using scratch card. Login as admin, go to global settings menu then select school setup. Down the form you will see Ewallet(Scratch Card Pin) field. 

Meanwhile, on how to create account please visit https://github.com/igweze/wizgrade/issues/2.

Best Regards

**Comment by packerdency** [comment]
@igweze ,am talking about parents,are we going to create them one by one or bulk upload,how can parents be link to children

**Comment by igweze** [comment]
@packerdency Parents are automatically link to their children. When you create a new student, the system will also create a new parent with their dashboard login details like the student too
