### ISSUE TITLE
Database Connection failed

### ISSUE THREAD

**Issue by OpenNoob** [igweze/wizgrade#5]
Hello thanks for your great software.

We wanted to try it out but when installing we got this error

Ooops Database Error: SQLSTATE[HY000]: General error: 1364 Field 'a_unique' doesn't have a default value

then we tried setting the a_unique default value to null and it continued to install bit on stage 4 of installation, there's another error. 

Oooops Database Connection failed: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date_idgsi'

We are using lamp stack, phpmyadmin to test.

**Comment by igweze** [comment]
@OpenNoob you are highly welcome.

Sorry about that bugs. Please kindly go this table **'nkiruka_wizgrade_access'** change this field **'a_unique'** default to null. This has been now fixed on the code.

Invalid default value for **'date_idgsi'** has  default value for datetime (NOT NULL DEFAULT '0000-00-00 00:00:00') which MySQL 5.7 defaults is disallowing 0000-00-00 00:00:00 as default value. Please locate this table **`wizgrade_cw_ireport`** and remove the default value **0000-00-00 00:00:00** from the **date_idgsi** field.

More so, will advice you re-download the updated install folder only.
