### ISSUE TITLE
Syntax error in wizGrade.sql

### ISSUE THREAD

**Issue by ph27** [igweze/wizgrade#6]
There is a syntax error in line 2739 of wizGrade.sql. There is an extra comma at the end. Sorry, I'm new to github so I don't know how to make the change for you.

orig:
  `date_idgsi` datetime NOT NULL,
new:
  `date_idgsi` datetime NOT NULL

**Comment by igweze** [comment]
@ph27 Thanks so much for the correction. I have updated the SQL file.
