### ISSUE TITLE
Nursery Student Bulk Upload/ Admit Student Error

### ISSUE THREAD

**Issue by adegbuyikk** [igweze/wizgrade#7]
Dear Igweze,
I encountered this error while uploading students and when admitting student after online application;

_**Ooops Database Error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens**_ 

Kindly help to review it appropriately.

**Comment by igweze** [comment]
@adegbuyikk  

Did you manually delete any column from the database ?

Did you export the excel from the system ?

Did you manually  add/remove column from the excel files.

This might be the issue here because it seem the database and excel file doesn't match or correspond.

Thanks

**Comment by adegbuyikk** [comment]
Thank you for your feedback.
1. I didn't alter the database
2. I didn't add/remove any column in excel
3. I have downloaded the excel from the system and it was used for Primary and Secondary. Only the Nursery section has issue.

Thank you

**Comment by igweze** [comment]
@adegbuyikk Good to hear from you again,

The issue is that the database and excel file doesn't match, please can you manually and separately count the field to know if the match. Thanks
