### ISSUE TITLE
CBT Examination Scores Not Recoverable

### ISSUE THREAD

**Issue by adegbuyikk** [igweze/wizgrade#8]
Dear Igweze,
Firsly, I appreciate your effort for this good job.

1. After a students completed the CBT Exam/Assignment, the score displays immediately but there is no link where the CBT scores can be viewed later.

2. Teacher/Admin can not also confirm/see the score of the attempted exam/assignment

3. Students should be able to submit before the time elapse/expire in case student has finished before the allocated time

4. Teacher/Admin should be able to set Number of Attempt for the CBT and the attempt times should show in the students page

Thanks for your consideration

**Comment by igweze** [comment]
@adegbuyikk  So sorry for replying this late.

Meanwhile, you are highly welcome. All you listed above are been taken care in the next upgrade coming soon by end of the year. 

Best Regards

**Comment by adegbuyikk** [comment]
@igweze 
Thanks for your response and good to hear that.
I appreciate your great effort

**Comment by packerdency** [comment]
> @adegbuyikk So sorry for replying this late.
> 
> Meanwhile, you are highly welcome. All you listed above are been taken care in the next upgrade coming soon by end of the year.
> 
> Best Regards

The year is almost coming to an end, are we still expecting the upgrade?

**Comment by igweze** [comment]
@packerdency wizGrade upgrade will be coming soon this year.

Has been busy with a project

Best Regards
